runtime: php
env: flex

handlers:
- url: /(.+\.(ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|otf|css|js))$
  static_files: \1
  upload: .+\.(ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|otf|css|js)$

- url: /.*
  script: auto